language: rust

sudo: required
dist: trusty

before_install:
  - curl https://sh.rustup.rs -sSf > rustup.sh
  - chmod +x rustup.sh
  - ./rustup.sh -y
  - export PATH=$HOME/.cargo/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:wpilib/toolchain'
      - kalakris-cmake
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - frc-toolchain
      - qemu

install:
  - source ~/.cargo/env
  - rustup target add arm-unknown-linux-gnueabi
  - ./on_nightly cargo install clippy
  - cargo install cargo-travis
  #- echo "[target.arm-unknown-linux-gnueabi]" >> ~/.cargo/config
  #- echo 'linker = "arm-frc-linux-gnueabi-gcc"' >> ~/.cargo/config

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

script:
  - cd frcredox_hal; cargo rustc --verbose -- -D warnings; cargo coverage && cd ../
  - cd frcredox; cargo rustc --verbose -- -D warnings; cargo coverage && cd ../
  - cd frcredox_hal; env CC="arm-frc-linux-gnueabi-gcc" cargo rustc --verbose --target=arm-unknown-linux-gnueabi -- -D warnings && cd ../
  - cd frcredox; env CC="arm-frc-linux-gnueabi-gcc" cargo rustc --verbose --target=arm-unknown-linux-gnueabi -- -D warnings && cd ../
  - ./on_nightly "cd frcredox_hal; cargo clippy"
  - ./on_nightly "cd frcredox; cargo clippy"
  - ./on_nightly "cd frcredox_hal; env CC=\"arm-frc-linux-gnueabi-gcc\" cargo clippy --target=arm-unknown-linux-gnueabi"
  - ./on_nightly "cd frcredox; env CC=\"arm-frc-linux-gnueabi-gcc\" cargo clippy --target=arm-unknown-linux-gnueabi"
