language: rust

sudo: required
dist: trusty

before_install:
  - curl https://sh.rustup.rs -sSf > rustup.sh
  - chmod +x rustup.sh
  - ./rustup.sh -y
  #- cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:wpilib/toolchain'
      - kalakris-cmake
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
      - frc-toolchain
      - qemu

install:
  - source ~/.cargo/env
  - rustup target add arm-unknown-linux-gnueabi
  #- echo "[target.arm-unknown-linux-gnueabi]" >> ~/.cargo/config
  #- echo 'linker = "arm-frc-linux-gnueabi-gcc"' >> ~/.cargo/config

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

#before_script:
#  - cargo install cargo-travis && export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --verbose
  - env CC="arm-frc-linux-gnueabi-gcc" cargo build --verbose --target=arm-unknown-linux-gnueabi
