[package]
name = "FRCRedox"
version = "0.0.1"
authors = ["OpenFRC Initiative"]

[dependencies]
futures = "^0.1"
error-chain = "^0.10"
clippy = {version = "*", optional = true}

[lib]
name = "frcredox"
path = "src/lib.rs"
build = "build.rs"
