[package]
name = "frcredox_hal"
version = "0.0.1"
authors = ["OpenFRC Initiative"]

[dependencies]
futures = "^0.1"
error-chain = "^0.10"
gcc = "0.3"

[lib]
name = "frcredox_hal"
path = "src/lib.rs"
build = "build.rs"
