[package]
name = "frcredox"
version = "0.0.1"
authors = ["OpenFRC Initiative"]

[dependencies]
futures = "^0.1"
error-chain = "^0.10"
clippy = {version = "*", optional = true}

[build-dependencies]
gcc = "^0.3"
